name: xarray-climate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.7
  - ipython=9.5.0
  - pyside6=6.9.2
  - aiobotocore=2.24.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - anyio=4.10.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async_lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - bleach=6.2.0
  - blinker=1.9.0
  - bokeh=3.8.0
  - botocore=1.40.18
  - brotli=1.1.0
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cartopy=0.25.0
  - cdsapi=0.7.7
  - certifi=2025.10.5
  - cffi=1.17.1
  - cftime=1.6.4
  - charset_normalizer=3.4.3
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - crc32c=2.7.1
  - cryptography=45.0.7
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2025.9.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - distributed=2025.9.1
  - donfig=0.8.1.post1
  - eofs=0.0.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fastjsonschema=2.21.2
  - fonttools=4.59.2
  - fqdn=1.5.1
  - frozenlist=1.7.0
  - fsspec=2025.9.0
  - gcsfs=2025.9.0
  - google_auth_oauthlib=1.2.2
  - google_crc32c=1.7.1
  - h11=0.16.0
  - h2=4.3.0
  - h5netcdf=1.6.4
  - h5py=3.14.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib_metadata=8.7.0
  - intake=2.0.8
  - ipykernel=6.30.1
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema_specifications=2025.9.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_lsp=2.3.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.9
  - lark=1.2.2
  - llvmlite=0.45.1
  - locket=1.0.0
  - lz4=4.4.4
  - markupsafe=3.0.2
  - matplotlib=3.9.4
  - matplotlib_inline=0.1.7
  - mistune=3.1.4
  - msgpack=1.1.1
  - multidict=6.6.3
  - multiurl=0.3.7
  - munkres=1.1.4
  - narwhals=2.5.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbformat=5.10.4
  - nest_asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.5
  - notebook_shim=0.2.4
  - numba=0.62.1
  - numcodecs=0.16.1
  - numpy=2.3.3
  - oauthlib=3.3.1
  - openpyxl=3.1.5
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.2
  - pandocfilters=1.5.0
  - parso=0.8.5
  - partd=1.4.2
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - plotly=6.4.0
  - prometheus_client=0.22.1
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pyasn1=0.6.1
  - pyasn1_modules=0.4.2
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.4
  - pypdf=6.5.0
  - pyproj=3.7.2
  - pytz=2025.2
  - pyu2f=0.1.5
  - referencing=0.36.2
  - requests=2.32.5
  - requests_oauthlib=2.0.0
  - rfc3339_validator=0.1.4
  - rfc3986_validator=0.1.1
  - rfc3987_syntax=1.1.0
  - rsa=4.9.1
  - s3fs=2025.9.0
  - scipy=1.16.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shap=0.48.0
  - shapely=2.1.1
  - shiboken6=6.9.2
  - six=1.17.0
  - slicer=0.0.8
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - stack_data=0.6.3
  - tblib=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025.2
  - uri_template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - wrapt=1.17.3
  - xarray=2025.9.0
  - xgboost=3.1.1
  - xyzservices=2025.4.0
  - yarl=1.20.1
  - zarr=3.1.3
  - zict=3.0.0
  - zipp=3.23.0
  - zstandard=0.25.0